
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using SSOL88.Popup;

namespace SSOL88.Counsult
{
    public partial class frm_수주관리 : Form
    {
        public frm_수주관리()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            //sqlDataSource3.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource3.FillAsync();
        }
        MySqlConnection connection = new MySqlConnection("Server=112.140.64.121;port=3306;database=dkdb;username=ssol88;password=defcon33@@dd;charset=utf8");
        MySqlCommand command;


        static string constring = "Server=112.140.64.121;Database=dkdb;Uid=ssol88;Pwd=defcon33@@dd;charset=utf8";
        MySqlConnection conn = new MySqlConnection(constring);
        DataTable dt = new DataTable();

        public void populateDGV()
        {
            string selectQuery = "Select * from ba";
            DataTable table = new DataTable();
            MySqlDataAdapter adapter = new MySqlDataAdapter(selectQuery, connection);
            MySqlCommand cmd = new MySqlCommand(selectQuery, connection);
            adapter.Fill(table);
            gridControl3.DataSource = table;
        }

      


        public void openConnection()
        {
            if (connection.State == ConnectionState.Closed)
            {
                connection.Open();
            }
        }
        public void closeConnection()
        {
            if (connection.State == ConnectionState.Open)
            {
                connection.Close();
            }
        }

        public void excuteQuery(string query)
        {
            try
            {
                openConnection();
                command = new MySqlCommand(query, connection);
                if (command.ExecuteNonQuery() == 1)
                {
                    MessageBox.Show("완료되었습니다");
                }
                else
                {
                    MessageBox.Show("실패했습니다");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            finally
            {
                closeConnection();
            }
        }

        public void searchData(string valueToFind)
        {
            string searchQuery = "select * from  ba where  concat(제품명) Like  '%" + valueToFind + "%'";
            MySqlDataAdapter adapter = new MySqlDataAdapter(searchQuery, connection);
            DataTable table = new DataTable();
            adapter.Fill(table);
            gridControl2.DataSource = table;

        }






        private void fnLoadGridControl()
        {
            // gridView, 스크롤 보이게 설정
          
       
        }


        private void gridControl2_Click(object sender, EventArgs e)
        {

        }

        private void frm_수주관리_Load(object sender, EventArgs e)
        {
            filldata();
        }

        private void filldata()
        {
            MySqlDataAdapter adapter = new MySqlDataAdapter();
            MySqlCommand cmd;

            //SQL
            string sql = "select * from ba ";
            cmd = new MySqlCommand(sql, conn);
            adapter.SelectCommand = cmd;

            //Bind datagrid

            adapter.Fill(dt);
            gridControl2.DataSource = dt;

        }

        public void fillData2()
        {
            MySqlDataAdapter adapter = new MySqlDataAdapter();
            MySqlCommand cmd;

            //SQL
            string sql = "select * from ba_d";
            cmd = new MySqlCommand(sql, conn);
            adapter.SelectCommand = cmd;

            //Bind datagrid

            adapter.Fill(dt);
            gridControl2.DataSource = dt;
        }

        private void button_수정_Click(object sender, EventArgs e)
        {

           // string updateQuery = "Update ag set 상담일='" + dateTimePicker_상담일.Text + "',접수일='" + dateTimePicker_접수일.Text + "',출하일='" + dateTimePicker_출하일.Text + "',외주일='" + dateTimePicker_외주일.Text + "',납기일='" + dateTimePicker_납기일.Text + "',거래처코드='" + textBox_거래처코드.Text + "',품목코드='" + textBox_품목코드.Text + "',진행상태='" + textBox_진행상태.Text + "',출하구분='" + textBox_출하구분.Text + "',특기사항='" + textBox_특기사항.Text + "',주문수량='" + textBox_주문수량.Text + "',생산수량='" + textBox_생산수량.Text + "',출하수량='" + textBox_출하수량.Text + "',미출고='" + textBox_미출고.Text + "',잔량='" + textBox_잔량.Text +"',납품단가= '"+textBox_납품단가.Text+"',수주금액='"+textBox_수주금액.Text+"',운송비='"+textBox_운송비.Text+"',수주중량='"+textBox_수주중량.Text+"',출하중량='"+textBox_출하중량.Text+"',외주중량='"+textBox_외주중량.Text+"',창고수량='"+textBox_창고수량.Text+ "where 수주코드=" + textBox_수주코드.Text + "';";
           // excuteQuery(updateQuery);
            //populateDGV();
        }


        private void button_저장_Click(object sender, EventArgs e)
        {
           
            
            //string insertQuery = "insert into ag(수주코드,상담일,접수일,출하일,외주일,납기일,거래처코드,품목코드,진행상태,출하구분,특기사항,주문수량,생산수량,미출고,잔량,납품단가,수주금액,운송비,수주중량,출하중량,외주중량,창고수량) values('" + textBox_수주코드.Text + "','" + dateTimePicker_상담일.Text + "','" +dateTimePicker_접수일.Text + "','" + dateTimePicker_납기일.Text + "','" + textBox_거래처코드.Text + "','" + textBox_품목코드.Text + "','" + textBox_진행상태.Text + "','" + textBox_출하구분.Text + "','" + textBox_특기사항.Text + "','" + textBox_주문수량.Text + "','" + textBox_생산수량.Text + "','" + textBox_출하수량.Text + "','" + textBox_미출고.Text + "','" + textBox_잔량.Text + "','" + textBox_납품단가.Text + "' , '" + textBox_수주금액.Text + "' , '" + textBox_운송비.Text + "' , '" + textBox_수주중량.Text + "','" + textBox_출하중량.Text+ "','"+textBox_외주중량.Text+"','"+textBox_창고수량.Text+"')";
            //MySqlCommand command = new MySqlCommand(insertQuery, connection);
           // MySqlDataAdapter adapter = new MySqlDataAdapter(command);
            //DataTable table = new DataTable();
            //adapter.Fill(table);
            //dataGridView_수주관리.DataSource = table;
            //populateDGV();
        }

        private void button_삭제_Click(object sender, EventArgs e)
        {

           // string deleteQuery = "delete from ag where 수주코드='" + textBox_수주코드.Text + "';";
            //excuteQuery(deleteQuery);
            //populateDGV();
        }

        private void dataGridView_수주관리_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void button8_Click(object sender, EventArgs e)
        {

        }

        private void 검색_Click(object sender, EventArgs e)
        {

        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            DataView dv = new DataView(dt);
            if (comboBox1.SelectedItem.ToString() == "전체")
            {
                gridControl2.DataSource = dt;
            }
            else
            {
                dv.RowFilter = string.Format("업체명 like '%{0}%'", comboBox1.SelectedItem.ToString());
            }
            gridControl2.DataSource = dv;



            /*
            DataView dv = new DataView(dt);
            if (comboBox1.SelectedItem.ToString() == "All")
            {
                gridControl3.DataSource = dt;
            }
            else
            {
                dv.RowFilter = string.Format("전체거래처", comboBox1.SelectedItem.ToString());
                populateDGV();
            }
            gridControl3.DataSource = dv;
            */
        }

        private void comboBox2_SelectedIndexChanged(object sender, EventArgs e)
        {
            DataView dv = new DataView(dt);
            if (comboBox1.SelectedItem.ToString() == "All")
            {
                gridControl2.DataSource = dt;
            }
            else
            {
                dv.RowFilter = string.Format("업체명 like '%{0}%'", comboBox1.SelectedItem.ToString());
            }
            gridControl2.DataSource = dv;
        }

        //MySqlConnection mcon = new MySqlConnection("datasource=112.140.64.121;port=3306;username=ssol88;password=defcon33@@dd");

        private void 조회기간검색_Click(object sender, EventArgs e)
        {

            MySqlConnection con = new MySqlConnection("Server=112.140.64.121;port=3306;database=dkdb;username=ssol88;password=defcon33@@dd;charset=utf8");
            DataTable dt = new DataTable();
            string query = "select * from ba where 접수일 between @data1 and @data2 ";
            MySqlDataAdapter da = new MySqlDataAdapter(query, con);
            da.SelectCommand.Parameters.AddWithValue("@data1", dateTimePicker1.Value);
            da.SelectCommand.Parameters.AddWithValue("@data2", dateTimePicker2.Value);
            da.Fill(dt);
            gridControl2.DataSource = dt;

            /*
            string selectQuery = "Select * from ba";
            DataTable table = new DataTable();
            MySqlDataAdapter adapter = new MySqlDataAdapter(selectQuery, connection);
            MySqlCommand cmd = new MySqlCommand(selectQuery, connection);
            adapter.Fill(table);
            gridControl2.DataSource = table;
            */


            //datetime 조회 하는 로직

            //DateTime dtFrom = Convert.ToDateTime(수주조회기간1.Text); //some DateTime value, e.g. DatePicker1.Text;
            //DateTime dtTo = Convert.ToDateTime(수주조회기간2.Text); //some DateTime value, e.g. DatePicker1.Text;
            // MySqlDataAdapter sdf = new MySqlDataAdapter("select * from dkdb.ba where 상담일 between '" + datetimepicker1.Value.ToString() + "' and '" + datetimepicker2.Value.ToString() + "'", mcon);
            //  DataTable sd = new DataTable();
            // sdf.Fill(sd);
            //gridControl2.DataSource = sd;
            //gridControl2.Refresh();
            //mcon.Close();
        }

        private void gridView3_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            
        }

        private void gridControl2_Click_1(object sender, EventArgs e)
        {

        }

        private void 추가_Click(object sender, EventArgs e)
        {
            수주관리팝업 frm = new 수주관리팝업(this);
            frm.Show();
        }

        private void 수정_Click(object sender, EventArgs e)
        {

            수주관리팝업 수주관리팝업 = new 수주관리팝업(this);
            수주관리팝업.Show();
        }

        private void 삭제_Click(object sender, EventArgs e)
        {

        }

        private void 수주조회기간1_ValueChanged(object sender, EventArgs e)
        {

        }

        private void datetimepicker2_ValueChanged(object sender, EventArgs e)
        {

        }

        private void dateTimePicker1_ValueChanged(object sender, EventArgs e)
        {


        }

        private void dateTimePicker2_ValueChanged_1(object sender, EventArgs e)
        {

        }

        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            수주관리팝업 수주관리팝업 = new 수주관리팝업(this);
            수주관리팝업.Show();
        }

        private void 거래처명_TextChanged(object sender, EventArgs e)
        {
            searchData(제품명.Text);
        }

        private void gridView1_DoubleClick(object sender, EventArgs e)
        {
           
        }

        private void gridView1_RowClick_1(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            fillData2();
        }
    }
}
