using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
namespace SSOL88.Counsult
{
    public partial class frm_품목정보 : Form
    {
        public frm_품목정보()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        MySqlConnection connection = new MySqlConnection("Server=112.140.64.121;port=3306;database=dkdb;username=ssol88;password=defcon33@@dd;charset=utf8");
        MySqlCommand command;


        static string constring = "Server=112.140.64.121;Database=dkdb;Uid=ssol88;Pwd=defcon33@@dd;charset=utf8";
        MySqlConnection conn = new MySqlConnection(constring);
        DataTable dt = new DataTable();

        public void populateDGV()
        {
            //string selectQuery = "Select * from ag";
            //DataTable table = new DataTable();
            //MySqlDataAdapter adapter = new MySqlDataAdapter(selectQuery, connection);
            //MySqlCommand cmd = new MySqlCommand(selectQuery, connection);
            //adapter.Fill(table);
            //dataGridView_품목정보.DataSource = table;

        }


        public void openConnection()
        {
            if (connection.State == ConnectionState.Closed)
            {
                connection.Open();
            }
        }
        public void closeConnection()
        {
            if (connection.State == ConnectionState.Open)
            {
                connection.Close();
            }
        }

        public void excuteQuery(string query)
        {
            try
            {
                openConnection();
                command = new MySqlCommand(query, connection);
                if (command.ExecuteNonQuery() == 1)
                {
                    MessageBox.Show("Query Executed");
                }
                else
                {
                    MessageBox.Show("Query Not Executed");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            finally
            {
                closeConnection();
            }
        }

        private void btn_추가_Click(object sender, EventArgs e)
        {
            //string insertQuery = "insert into ag(제품코드,영문품명,한글품명,고객사코드,납품단가,개발일자,양산일자,단위,제품중량,기계가공,재질,공정,도면사진,제품사진,금형코드,지그코드,단가고정,로스율) values('" + textBox_제품코드.Text + "','" + textBox_품명_영문.Text + "','" + textBox_품명_한글.Text + "','" + textBox_고객사코드.Text + "','" + textBox_납품단가.Text + "','" + dateTimePicker_개발일자.Text + "','" + dateTimePicker_양산일자.Text + "','" + textBox_단위.Text + "','" + textBox_제품중량.Text + "','" + textBox_기계가공.Text + "','" + textBox_재질.Text + "','" + textBox_공정.Text + "','" + textBox_도면코드.Text + "','" + textBox_제품사진.Text + "','" + textBox_금형코드.Text + "' , '" + textBox_지그코드.Text + "' , '" + textBox_단가고정.Text + "' , '" + textBox_로스율.Text + "');";
            //MySqlCommand command = new MySqlCommand(insertQuery, connection);
            //MySqlDataAdapter adapter = new MySqlDataAdapter(command);
            //DataTable table = new DataTable();
            //adapter.Fill(table);
            //dataGridView_품목정보.DataSource = table;
            //populateDGV();
        }

        private void btn_수정_Click(object sender, EventArgs e)
        {
            //string updateQuery = "Update ag set 제품코드='" + textBox_제품코드.Text + "',영문품명='" + textBox_품명_영문.Text + "',한글품명='" + textBox_품명_한글.Text + "',고객사코드='" + textBox_고객사코드.Text + "',납품단가='" + textBox_납품단가.Text + "',개발일자='" + dateTimePicker_개발일자.Text + "',양산일자='" + dateTimePicker_양산일자.Text + "',단위='" + textBox_단위.Text + "',제품중량='" + textBox_제품중량.Text + "',기계가공='" + textBox_기계가공.Text + "',재질='" + textBox_재질.Text + "',도면사진='" + textBox_도면코드.Text + "',제품사진='" + textBox_제품사진.Text + "',금형코드='" + textBox_금형코드.Text + "',금형코드='" + textBox_금형코드.Text + "',지그코드='" + textBox_지그코드.Text + "where 제품코드=" + textBox_제품코드.Text + "';";
            //excuteQuery(updateQuery);
            //populateDGV();
        }

        private void btn_삭제_Click(object sender, EventArgs e)
        {
            //string deleteQuery = "delete from aa where 제품코드='" + textBox_제품코드.Text + "';";
            //excuteQuery(deleteQuery);
            //populateDGV();
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            //MySqlConnection connection = new MySqlConnection("Server=112.140.64.121;port=3306;database=dkdb;username=ssol88;password=defcon33@@dd;charset=utf8");
            //string searchQuery = "select * from ag where 한글품명 like '%" + textBox_제품명.Text + "%'";
            //MySqlCommand command = new MySqlCommand(searchQuery, connection);

            //MySqlDataAdapter adapter = new MySqlDataAdapter(command);
            //DataTable table = new DataTable();
            //adapter.Fill(table);
            //dataGridView_품목정보.DataSource = table;
        }

        private void frm_품목정보_Load(object sender, EventArgs e)
        {

        }

        private void dataGridView_품목정보_MouseClick(object sender, MouseEventArgs e)
        {
            //textbox_제품코드.text = datagridview_품목정보.currentrow.cells[0].value.tostring();
            //textbox_품명_영문.text = datagridview_품목정보.currentrow.cells[1].value.tostring();
            //textbox_품명_한글.text = datagridview_품목정보.currentrow.cells[2].value.tostring();
            //textbox_고객사코드.text = datagridview_품목정보.currentrow.cells[3].value.tostring();
            //textbox_납품단가.text = datagridview_품목정보.currentrow.cells[4].value.tostring();
            //datetimepicker_개발일자.text = datagridview_품목정보.currentrow.cells[5].value.tostring();
            //datetimepicker_양산일자.text = datagridview_품목정보.currentrow.cells[6].value.tostring();
            //textbox_단위.text = datagridview_품목정보.currentrow.cells[7].value.tostring();
            //textbox_제품중량.text = datagridview_품목정보.currentrow.cells[8].value.tostring();
            //textbox_기계가공.text = datagridview_품목정보.currentrow.cells[9].value.tostring();
            //textbox_재질.text = datagridview_품목정보.currentrow.cells[10].value.tostring();
            //textbox_공정.text = datagridview_품목정보.currentrow.cells[11].value.tostring();
            //textbox_도면코드.text = datagridview_품목정보.currentrow.cells[12].value.tostring();
            //textbox_제품사진.text = datagridview_품목정보.currentrow.cells[13].value.tostring();
            //textbox_금형코드.text = datagridview_품목정보.currentrow.cells[14].value.tostring();
        }

        private void button2_Click(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {

        }

        private void button5_Click(object sender, EventArgs e)
        {

        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void button4_Click(object sender, EventArgs e)
        {

        }

        private void textBox7_TextChanged(object sender, EventArgs e)
        {

        }

        private void button3_Click(object sender, EventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void button6_Click(object sender, EventArgs e)
        {

        }

        private void comboBox4_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void comboBox5_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void button7_Click(object sender, EventArgs e)
        {

        }

        private void comboBox6_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void button8_Click(object sender, EventArgs e)
        {

        }

        private void comboBox7_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void button9_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox2_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox3_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox4_Click(object sender, EventArgs e)
        {

        }

        private void splitContainer2_Panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void splitContainer3_Panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void button6_Click_1(object sender, EventArgs e)
        {

        }

        private void splitContainer3_Panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void pictureBox4_Click_1(object sender, EventArgs e)
        {

        }

        private void button1_Click_1(object sender, EventArgs e)
        {

        }

        private void pictureBox1_Click_1(object sender, EventArgs e)
        {

        }

        private void comboBox2_SelectedIndexChanged_1(object sender, EventArgs e)
        {

        }

        private void button6_Click_2(object sender, EventArgs e)
        {

        }

        private void comboBox2_SelectedIndexChanged_2(object sender, EventArgs e)
        {

        }

        private void comboBox1_SelectedIndexChanged_1(object sender, EventArgs e)
        {
            DataView dv = new DataView(dt);
            if (comboBox1.SelectedItem.ToString() == "All")
            {
                gridControl2.DataSource = dt;
            }
            else
            {
                dv.RowFilter = string.Format("제품구분 like '%{0}%'", comboBox1.SelectedItem.ToString());
            }
            gridControl2.DataSource = dv;
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void splitContainer1_Panel1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
